/* Kriaat Hub — landing page objetiva para geração de leads. */
import { FormEvent, useEffect, useRef, useState } from "react";
import { ArrowRight, Check, MessageCircle, Send, X } from "lucide-react";
import { trpc } from "@/lib/trpc";

function Logo() {
  return <a href="#inicio" className="flex items-center gap-3" aria-label="Kriaat Hub"><svg width="36" height="40" viewBox="0 0 40 40" fill="none" aria-hidden="true"><path d="M20 4c-6.6 0-12 5.2-12 11.6 0 4.2 2.3 7 4.4 9 1.3 1.3 2 2.7 2 4.4v2h11.2v-2c0-1.7.7-3.1 2-4.4 2.1-2 4.4-4.8 4.4-9C32 9.2 26.6 4 20 4z" stroke="#FFB000" strokeWidth="1.9" strokeLinejoin="round" /><path d="M15.5 34h9M16.5 37h7" stroke="#FFB000" strokeWidth="1.9" strokeLinecap="round" /><path d="M17 22c-1-1-1.6-2-1.6-3.4 0-2.4 2-4.3 4.6-4.3" stroke="#FFB000" strokeWidth="1.5" strokeLinecap="round" /><path d="M20 1v3M11 5l1.8 2.2M29 5l-1.8 2.2" stroke="#FFB000" strokeWidth="1.6" strokeLinecap="round" /></svg><span className="brand-wordmark flex items-center gap-1.5 text-[1.55rem] leading-none text-[#F7F6FA]"><span>kriaat</span><span className="h-4 w-px bg-[#B38CFF]/70" /><span className="font-semibold text-[#B38CFF]">hub</span></span></a>;
}

type LeadData = { name: string; phone: string; business: string; invests: string; objective: string; budget: string };
const initialLead: LeadData = { name: "", phone: "", business: "", invests: "", objective: "", budget: "" };

function LeadChat({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [step, setStep] = useState(0);
  const [lead, setLead] = useState<LeadData>(initialLead);
  const [input, setInput] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const [submitError, setSubmitError] = useState("");
  const [consentAccepted, setConsentAccepted] = useState(false);
  const submitLead = trpc.leads.create.useMutation();
  const inputRef = useRef<HTMLInputElement>(null);
  const questions = [
    { key: "name", label: "Como podemos chamar você?", placeholder: "Seu nome", type: "input" },
    { key: "phone", label: "Qual é o seu WhatsApp?", placeholder: "(47) 99999-9999", type: "tel" },
    { key: "business", label: "Qual é o nome do seu negócio?", placeholder: "Ex.: clínica, loja, restaurante...", type: "input" },
    { key: "invests", label: "Você já investe em tráfego pago?", placeholder: "Escolha uma opção", type: "options", options: ["Ainda não", "Sim, mas sem consistência", "Sim, e quero melhorar", "Já investi e parei"] },
    { key: "objective", label: "O que você mais quer melhorar?", placeholder: "Escolha uma opção", type: "options", options: ["Receber mais conversas", "Gerar agendamentos", "Atrair visitas ou ligações", "Vender um serviço específico"] },
    { key: "budget", label: "Qual faixa de verba mensal você imagina para anúncios?", placeholder: "Escolha uma opção", type: "options", options: ["Ainda não sei", "Até R$ 1.000", "De R$ 1.000 a R$ 3.000", "Acima de R$ 3.000"] },
  ] as const;
  const current = questions[step];
  useEffect(() => { if (!open) return; setStep(0); setLead(initialLead); setInput(""); setSubmitted(false); setSubmitError(""); setConsentAccepted(false); submitLead.reset(); window.setTimeout(() => inputRef.current?.focus(), 120); }, [open]);
  useEffect(() => { if (!open) return; const previous = document.body.style.overflow; const escape = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; document.body.style.overflow = "hidden"; window.addEventListener("keydown", escape); return () => { document.body.style.overflow = previous; window.removeEventListener("keydown", escape); }; }, [open, onClose]);
  if (!open) return null;
  const advance = async (value: string) => { if (submitLead.isPending) return; if (step === questions.length - 1 && !consentAccepted) return; const nextLead = { ...lead, [current.key]: value }; setLead(nextLead); setInput(""); setSubmitError(""); if (step === questions.length - 1) { try { const params = new URLSearchParams(window.location.search); await submitLead.mutateAsync({ ...nextLead, source: "kriaat-trafego-pago", page: window.location.pathname, utmSource: params.get("utm_source") ?? undefined, utmMedium: params.get("utm_medium") ?? undefined, utmCampaign: params.get("utm_campaign") ?? undefined, utmContent: params.get("utm_content") ?? undefined, consent: true, createdAt: new Date().toISOString() }); setSubmitted(true); } catch { setSubmitError("Não conseguimos enviar agora. Confira os dados e tente novamente."); } } else { setStep((value) => value + 1); window.setTimeout(() => inputRef.current?.focus(), 80); } };
  const submitInput = (event: FormEvent) => { event.preventDefault(); if (input.trim()) void advance(input.trim()); };
  return <div className="chat-backdrop" role="dialog" aria-modal="true" aria-labelledby="chat-title" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="chat-modal"><header className="chat-header"><div className="chat-avatar"><MessageCircle size={19} /></div><div className="min-w-0 flex-1"><p id="chat-title">Kriaat Hub</p><span>Vamos entender o seu momento</span></div><button className="chat-close" onClick={onClose} aria-label="Fechar formulário"><X size={19} /></button></header><div className="chat-body">{submitted ? <div className="chat-success"><div className="success-icon"><Check size={23} /></div><p className="eyebrow text-[#17B26A]">Mensagem recebida</p><h2 className="display mt-3 text-2xl font-semibold">Obrigado, {lead.name.split(" ")[0]}.</h2><p className="mt-3 text-sm leading-6 text-[#14052B]/65">Recebemos suas respostas e vamos conversar sobre o melhor caminho para o seu negócio.</p><button className="button-dark mt-6" onClick={onClose}>Voltar para a página <ArrowRight size={16} /></button></div> : <><div className="chat-intro"><span className="chat-bubble">Oi. Vamos entender o que está impedindo o seu negócio de crescer?</span><small>Agora</small></div><div className="chat-progress"><span style={{ width: `${((step + 1) / questions.length) * 100}%` }} /></div><div className="chat-question"><p className="eyebrow text-[#14052B]/45">Pergunta {step + 1} de {questions.length}</p><h2 className="display mt-2 text-[1.45rem] font-semibold leading-tight">{current.label}</h2></div>{current.type === "options" ? <><div className="chat-options">{current.options?.map((option) => <button key={option} onClick={() => advance(option)} disabled={submitLead.isPending || (step === questions.length - 1 && !consentAccepted)}>{submitLead.isPending && step === questions.length - 1 ? "Enviando..." : option}<ArrowRight size={15} /></button>)}</div>{step === questions.length - 1 && <label className="consent-row"><input type="checkbox" checked={consentAccepted} onChange={(event) => setConsentAccepted(event.target.checked)} /> <span>Autorizo a Kriaat a usar estes dados para entrar em contato.</span></label>}</> : <form className="chat-form" onSubmit={submitInput}><input ref={inputRef} required type={current.type === "tel" ? "tel" : "text"} value={input} onChange={(event) => setInput(event.target.value)} placeholder={current.placeholder} aria-label={current.label} /><button type="submit" aria-label="Enviar resposta"><Send size={17} /></button></form>}{submitError && <p className="chat-error" role="alert">{submitError}</p>}<p className="chat-privacy">Seus dados serão usados somente para entrarmos em contato.</p></>}</div></div></div>;
}

export default function Home() {
  const [chatOpen, setChatOpen] = useState(false);
  return <div id="inicio" className="min-h-screen bg-[#14052B] text-[#F7F6FA]"><header className="site-header"><div className="mx-auto flex max-w-[1180px] items-center justify-between px-5 py-5 sm:px-8"><Logo /></div></header><main className="simple-landing"><section className="hero"><div className="hero-glow" /><div className="mx-auto flex max-w-[920px] items-center px-5 py-16 sm:px-8 sm:py-24 lg:min-h-[calc(100vh-82px)] lg:py-20"><div className="relative"><p className="eyebrow text-[#FFB000]">Seu negócio merece crescer</p><h1 className="display mt-5 max-w-[850px] text-[clamp(2.8rem,7vw,6.8rem)] font-semibold leading-[.94] tracking-[-.075em]">Seu negócio é bom, mas poucas pessoas chegam até você<span className="text-[#FFB000]">?</span></h1><p className="mt-7 max-w-[620px] text-[1.05rem] leading-7 text-[#F7F6FA]/68">Ajudamos você a ser mais conhecido, atrair mais clientes e transformar sua presença digital em oportunidades de venda.</p><button className="button-primary mt-9" onClick={() => setChatOpen(true)}>Quero vender mais <ArrowRight size={17} /></button></div></div></section></main><LeadChat open={chatOpen} onClose={() => setChatOpen(false)} /></div>;
}
