import { FormEvent, useEffect, useRef, useState } from "react";
import { ArrowRight, Check, MessageCircle, X } from "lucide-react";
import { trpc } from "@/lib/trpc";

function Logo() {
  return <a href="#inicio" className="brand-lockup" aria-label="Kriaat Hub"><svg width="34" height="38" viewBox="0 0 40 40" fill="none" aria-hidden="true"><path d="M20 4c-6.6 0-12 5.2-12 11.6 0 4.2 2.3 7 4.4 9 1.3 1.3 2 2.7 2 4.4v2h11.2v-2c0-1.7.7-3.1 2-4.4 2.1-2 4.4-4.8 4.4-9C32 9.2 26.6 4 20 4z" stroke="#FFB000" strokeWidth="1.9" strokeLinejoin="round" /><path d="M15.5 34h9M16.5 37h7M17 22c-1-1-1.6-2-1.6-3.4 0-2.4 2-4.3 4.6-4.3M20 1v3M11 5l1.8 2.2M29 5l-1.8 2.2" stroke="#FFB000" strokeWidth="1.6" strokeLinecap="round" /></svg><span className="brand-wordmark text-[1.45rem] leading-none text-[#F7F6FA]"><span>kriaat</span><span className="mx-1.5 inline-block h-4 w-px bg-[#B38CFF]/70" /><span className="font-semibold text-[#B38CFF]">hub</span></span></a>;
}

type LeadData = { name: string; phone: string; business: string; objective: string; situation: string };
const initialLead: LeadData = { name: "", phone: "", business: "", objective: "", situation: "" };

function LeadChat({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [step, setStep] = useState(0); const [lead, setLead] = useState(initialLead); const [input, setInput] = useState(""); const [submitted, setSubmitted] = useState(false); const [error, setError] = useState(""); const [consent, setConsent] = useState(false); const mutation = trpc.leads.create.useMutation(); const inputRef = useRef<HTMLInputElement>(null);
  const questions = [
    { key: "name", label: "Como podemos chamar você?", placeholder: "Seu nome", type: "input" },
    { key: "phone", label: "Qual é o seu WhatsApp?", placeholder: "(47) 99999-9999", type: "tel" },
    { key: "business", label: "Qual é o nome do seu negócio?", placeholder: "Ex.: clínica, loja, escritório...", type: "input" },
    { key: "objective", label: "O que você quer gerar com os anúncios?", type: "options", options: ["Mais conversas no WhatsApp", "Pedidos de orçamento", "Agendamentos", "Mais oportunidades comerciais"] },
    { key: "situation", label: "Você já anuncia na internet?", type: "options", options: ["Ainda não — quero começar", "Ainda não — quero entender como funciona", "Já anuncio, mas quero crescer", "Já anunciei e quero voltar"] },
  ] as const;
  const current = questions[step];
  useEffect(() => { if (!open) return; setStep(0); setLead(initialLead); setInput(""); setSubmitted(false); setError(""); setConsent(false); mutation.reset(); window.setTimeout(() => inputRef.current?.focus(), 100); }, [open]);
  useEffect(() => { if (!open) return; const old = document.body.style.overflow; const esc = (e: KeyboardEvent) => e.key === "Escape" && onClose(); document.body.style.overflow = "hidden"; window.addEventListener("keydown", esc); return () => { document.body.style.overflow = old; window.removeEventListener("keydown", esc); }; }, [open, onClose]);
  if (!open) return null;
  const advance = async (value: string) => { if (mutation.isPending || (step === 4 && !consent)) return; const next = { ...lead, [current.key]: value } as LeadData; setLead(next); setInput(""); setError(""); if (step < 4) { setStep(step + 1); window.setTimeout(() => inputRef.current?.focus(), 80); return; } try { const p = new URLSearchParams(window.location.search); await mutation.mutateAsync({ name: next.name, phone: next.phone, business: next.business, city: "", invests: next.situation, objective: next.objective, budget: "A definir no diagnóstico", source: "kriaat-trafego-pago", page: window.location.pathname, utmSource: p.get("utm_source") ?? undefined, utmMedium: p.get("utm_medium") ?? undefined, utmCampaign: p.get("utm_campaign") ?? undefined, utmContent: p.get("utm_content") ?? undefined, consent: true, createdAt: new Date().toISOString() }); setSubmitted(true); } catch { setError("Não conseguimos enviar agora. Tente novamente."); } };
  return <div className="chat-backdrop" role="dialog" aria-modal="true" aria-labelledby="chat-title" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><div className="chat-modal"><header className="chat-header"><div className="chat-avatar"><MessageCircle size={18} /></div><div className="min-w-0 flex-1"><p id="chat-title">Kriaat Hub</p><span>Vamos planejar seus anúncios</span></div><button className="chat-close" onClick={onClose} aria-label="Fechar formulário"><X size={19} /></button></header><div className="chat-body">{submitted ? <div className="chat-success"><div className="success-icon"><Check size={23} /></div><p className="eyebrow text-[#17B26A]">Recebemos seus dados</p><h2 className="display mt-3 text-2xl font-semibold">Obrigado, {lead.name.split(" ")[0]}.</h2><p className="mt-3 text-sm leading-6 text-[#14052B]/65">Vamos analisar seu momento e entrar em contato para falar sobre suas campanhas.</p><button className="button-dark mt-6" onClick={onClose}>Voltar para a página <ArrowRight size={16} /></button></div> : <><div className="chat-intro"><span className="chat-bubble">Vamos entender seu negócio e planejar os próximos passos.</span><small>Leva menos de um minuto</small></div><div className="chat-progress"><span style={{ width: `${((step + 1) / 5) * 100}%` }} /></div><div className="chat-question"><p className="eyebrow text-[#14052B]/45">Pergunta {step + 1} de 5</p><h2 className="display mt-2 text-[1.42rem] font-semibold leading-tight">{current.label}</h2></div>{current.type === "options" ? <><div className="chat-options">{current.options?.map((option) => <button key={option} onClick={() => advance(option)} disabled={mutation.isPending || (step === 4 && !consent)}>{option}<ArrowRight size={15} /></button>)}</div>{step === 4 && <label className="consent-row"><input type="checkbox" checked={consent} onChange={(e) => setConsent(e.target.checked)} /><span>Autorizo a Kriaat a usar estes dados para entrar em contato.</span></label>}</> : <form className="chat-form" onSubmit={(e: FormEvent) => { e.preventDefault(); if (input.trim()) void advance(input.trim()); }}><input ref={inputRef} required type={current.type === "tel" ? "tel" : "text"} value={input} onChange={(e) => setInput(e.target.value)} placeholder={current.placeholder} aria-label={current.label} /><button type="submit" aria-label="Enviar resposta"><ArrowRight size={17} /></button></form>}{error && <p className="chat-error" role="alert">{error}</p>}<p className="chat-privacy">Seus dados serão usados somente para entrarmos em contato.</p></>}</div></div></div>;
}

export default function Home() {
  const [open, setOpen] = useState(false); const showForm = () => setOpen(true);
  return <div id="inicio" className="new-landing"><main><section className="new-hero"><div className="new-hero-grid" /><header className="new-header"><Logo /><button className="new-header-link" onClick={showForm}>Quero anunciar minha empresa <ArrowRight size={15} /></button></header><div className="new-hero-content"><p className="new-kicker">ESTRATÉGIAS DIGITAIS PARA EMPRESAS QUE QUEREM CRESCER</p><h1 className="new-display">Sua empresa pode alcançar muito mais pessoas. <em>A estratégia é fazer isso do jeito certo.</em></h1><p className="new-hero-copy">Planejamos e gerenciamos a presença paga da sua empresa no Instagram, Facebook e Google para aumentar sua exposição, gerar interesse e abrir novos caminhos para clientes chegarem até você.</p><button className="new-primary" onClick={showForm}>Quero entender o que faz sentido para minha empresa <ArrowRight size={17} /></button><p className="new-proofline">META ADS <span>•</span> GOOGLE ADS <span>•</span> ESTRATÉGIA <span>•</span> OTIMIZAÇÃO</p></div><div className="new-hero-bottom"><span>UMA ESTRATÉGIA DIGITAL PARA SUA EMPRESA</span><span>UMA ESTRATÉGIA PARA AMPLIAR SUA PRESENÇA E CRIAR NOVOS PONTOS DE CONTATO COM O SEU PÚBLICO.</span></div></section>
    <section className="new-audience"><div className="new-section-intro"><p className="new-kicker dark">CRESCER NO DIGITAL NÃO É SIMPLESMENTE APARECER MAIS</p><h2 className="new-display dark">Sua empresa precisa aparecer para quem pode se interessar pelo que você oferece.<br /><span>E facilitar o caminho para essas pessoas chegarem até você.</span></h2><p>Cada empresa vende de um jeito e cada público procura de uma forma diferente. Antes de escolher onde anunciar, entendemos seu negócio, seu objetivo e como as pessoas costumam chegar até serviços ou produtos como o seu.</p></div><div className="audience-grid"><div><b>01</b><h3>Sua empresa precisa ampliar sua presença</h3><p>Estar presente nos canais certos aumenta as chances de mais pessoas conhecerem o que você oferece.</p></div><div><b>02</b><h3>Você precisa transformar atenção em contato</h3><p>Não basta aparecer. A campanha precisa dar ao interessado um caminho claro para falar com sua empresa.</p></div><div><b>03</b><h3>Cada negócio exige uma estratégia diferente</h3><p>Meta, Google, página, WhatsApp ou uma combinação entre eles: a estrutura depende do seu cenário.</p></div></div></section>
    <section className="new-problem"><div className="new-section-intro"><p className="new-kicker">COLOCAR UMA CAMPANHA NO AR É SÓ O COMEÇO</p><h2 className="new-display">O anúncio pode gerar atenção. Mas existe um caminho inteiro até uma venda acontecer.</h2><p>Canal, mensagem, oferta, criativo, página e atendimento influenciam o resultado. Por isso, olhar apenas para cliques ou alcance não conta a história inteira.</p></div><div className="problem-flow"><div><span>01</span><strong>Visibilidade</strong><small>Sua empresa está chegando às pessoas certas?</small></div><i>→</i><div><span>02</span><strong>Interesse</strong><small>A mensagem desperta atenção?</small></div><i>→</i><div><span>03</span><strong>Contato</strong><small>As pessoas estão chegando ao WhatsApp, formulário ou outro canal?</small></div><i>→</i><div><span>04</span><strong>Comercial</strong><small>O que acontece depois depende também do atendimento e da capacidade de venda da empresa.</small></div></div><div className="new-callout">NOSSO PAPEL É CONSTRUIR E MELHORAR O CAMINHO ATÉ O CONTATO. A VENDA É O RESULTADO DE TODO O PROCESSO.</div></section>
    <section className="new-method"><div className="method-heading"><p className="new-kicker dark">NOSSA FORMA DE TRABALHAR</p><h2 className="new-display dark">Primeiro entendemos o negócio. Depois decidimos quais ferramentas fazem sentido.</h2></div><div className="method-list"><div><span>01</span><div><h3>Entendemos seu negócio</h3><p>O que você oferece, quem você quer alcançar, onde atende e qual objetivo pretende atingir.</p></div></div><div><span>02</span><div><h3>Escolhemos a estratégia</h3><p>Escolhemos os canais e a estrutura mais coerentes com a forma como seu público descobre e procura o que você oferece.</p></div></div><div><span>03</span><div><h3>Criamos seus anúncios</h3><p>Estruturamos campanhas, públicos, objetivos e pontos de conversão para começar a gerar dados e contatos.</p></div></div><div><span>04</span><div><h3>Acompanhamos de perto</h3><p>Analisamos o desempenho e usamos os dados para melhorar continuamente as campanhas e a estratégia.</p></div></div></div><p className="method-note">META, GOOGLE, CRIATIVOS OU PÁGINAS SÃO FERRAMENTAS. A ESTRATÉGIA DEFINE COMO ELAS DEVEM TRABALHAR JUNTAS.</p><small className="method-subnote">Se a operação precisar de criativos, landing page, site ou Perfil da Empresa no Google, esses serviços podem ser contratados separadamente.</small></section>
    <section className="new-final"><p className="new-kicker">ENTENDA O MELHOR CAMINHO PARA SUA EMPRESA</p><h2 className="new-display">Conte um pouco sobre o seu negócio. A partir daí, definimos por onde faz sentido começar.</h2><p>Responda algumas perguntas rápidas sobre sua empresa, seu momento e seus objetivos. Isso nos ajuda a entender quais canais e soluções podem fazer sentido para sua estratégia digital.</p><button className="new-primary" onClick={showForm}>Quero entender o que faz sentido para minha empresa <ArrowRight size={17} /></button><small>Meta Ads, Google Ads ou uma combinação de soluções — a recomendação depende do seu negócio.</small></section><footer className="new-footer"><Logo /><span>Anúncios para empresas que querem crescer.</span></footer></main><LeadChat open={open} onClose={() => setOpen(false)} />
  </div>;
}
